### PR TITLE
add Team Tool Box App

### PR DESCRIPTION
**Pull request by lduboeuf**

### CODE REVIEW

**Comment by michielbdejong** [comment]
Great app! What did you use to build it? Does it use client-side templating? And how are collections/objects stored in remoteStorage?

**Comment by skddc** [comment]
When you try it and put some data in, you can check the `teams` category in e.g. https://remotestorage-browser.5apps.com

**Comment by lduboeuf** [comment]
thanks  @michielbdejong , i use doTjs for client side rendering and several stuffs , you can have a look in my github project: https://github.com/lduboeuf/team-tool-box
I will appreciate if you have any advice concerning data structuration, remostorage use or the project itself.

**Comment by skddc** [comment]
By the way, would be nice to explain the purpose of the app a bit more (readme and/or "About" page). I couldn't quite understand it.

**Comment by lduboeuf** [comment]
humm you did not find any About page ?

**Comment by skddc** [comment]
Yes, I did. But it doesn't really say what problem the app is solving, i.e. what it's supposed to be used for.

**Comment by lduboeuf** [comment]
allright, i will add some info soon thanks. As a trainer i use it within my group for practical exercices or projects choose a leader, etc...

**Comment by lduboeuf** [comment]
humm, i think i did not well defined paths, i have "/teams/team/xxxx" maybe should be enough(better) to have "/teams/xxxx" directly ?
As well for members of a teams, is it better to have a root path like "/peoples/xxxx"  and link them in an array in "/team/xxx/members" object ?

**Comment by skddc** [comment]
I think it would be better to discuss things like that over at https://community.remotestorage.io/c/app-development -- this is only the pull request for the app catalog page on the Unhosted website after all.

**Comment by lduboeuf** [comment]
oh yes sorry, i will ask there then

**Pull request merged**
