### PR TITLE
feat: add apps find

### PR DESCRIPTION
**Pull request by hugurp**
Adding a new unhosted app, Find.
- https://find.internet4000.com
- https://github.com/internet4000/find

Hope this fits!

### CODE REVIEW

**Comment by michielbdejong** [comment]
Great! Can you also add it at the same place in https://github.com/unhosted/website/blob/master/apps/source.html so  that  it is not overwritten next time we generate apps/index.html from apps/source.html. Thanks!

**Comment by hugurp** [comment]
Oups, sorry I did not see that before!
Thanks for the review, is it better now?

**Comment by michielbdejong** [comment]
yes, great! live on: https://unhosted.org/apps/?refresh=true

**Comment by hugurp** [comment]
Thank you!

**Pull request merged**
